app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "44"

finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=xdg-config/monitors.xml:ro
  - --filesystem=host-etc
  - --filesystem=host-os

cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'

modules:
  - name: blueprint-compiler
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.6.0/blueprint-compiler-v0.6.0.tar.bz2
        sha256: e8746dcbc66a002337614002ddf4ac075b5b0322eb7ec685f735ab37894ea5b9
    cleanup:
      - "*"

  - name: gdm-settings
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://github.com/realmazharhussain/gdm-settings/archive/refs/tags/v3.1.tar.gz
        sha256: 7a62c7d5c6d6caea4d4dfd6b446c43f55c9f3f2cbc1f41a2dc7d8a782d494e89
