app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "43"

finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=xdg-config/monitors.xml:ro
  - --filesystem=host-etc
  - --filesystem=host-os

cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'

modules:
  - name: blueprint-compiler
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.4.0/blueprint-compiler-v0.4.0.tar.bz2
        sha256: 316309c1527fbc7670aa3c41a7227452d129eedcad944c468ccce76bce70da3f
    cleanup:
      - "*"

  - name: gdm-settings
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://github.com/realmazharhussain/gdm-settings/archive/refs/tags/v2.1.tar.gz
        sha256: d00f5294d90ab755f8a93697d75fec119c1f874aca98d1f65fdbcf29e2cc774e
