app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "42"
finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=host-os
  - --filesystem=/etc/dconf/db/gdm.d
  - --filesystem=/etc/dconf/profile/gdm
cleanup:
  - /bin/blueprint-compiler
  - /lib/*/site-packages/blueprintcompiler
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'
modules:
  - name: blueprint-compiler
    builddir: true
    buildsystem: meson
    sources:
      - type: git
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
        commit: 3b39e0d541ed3f18441420228f1270bd167fa7fa
  - name: gdm-settings
    builddir: true
    buildsystem: meson
    config-opts:
      - --buildtype=release
    sources:
      - type: archive
        url: https://github.com/realmazharhussain/gdm-settings/archive/refs/tags/v0.5.2.tar.gz
        sha256: 9aa43fa7ed84e194a4f12e4691a4463a3199e7d3171aa363d5368144d361ba70
