app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "48"

finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=xdg-config/monitors.xml:ro
  - --filesystem=host-etc
  - --filesystem=host-os

cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'

modules:
  - name: blueprint-compiler
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.16.0/blueprint-compiler-v0.16.0.tar.bz2
        sha256: 77a5d593f433c8ca70a05390532cd186c60944cfa6bcd39296c1c2597a7a50fc
    cleanup:
      - "*"

  - name: gdm-settings
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://github.com/realmazharhussain/gdm-settings/archive/refs/tags/v5.0.tar.gz
        sha256: adfc33250589217531e9fa679cad03cbe7c845b39fb99fcc226329453ce0ac40
