app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "45"

finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=host-etc
  - --filesystem=host-os

cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'

modules:
  - name: blueprint-compiler
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.10.0/blueprint-compiler-v0.10.0.tar.bz2
        sha256: 9c3c6eecef9eb54ad43b9ef786697a9f99b21e35240e9ddc8541a2cbd9ea79ba
    cleanup:
      - "*"

  - name: gdm-settings
    builddir: true
    buildsystem: meson
    sources:
      - type: archive
        url: https://github.com/realmazharhussain/gdm-settings/archive/refs/tags/v4.2.tar.gz
        sha256: 0706eef5eb4317e3d3c9499950b27da65c670236f3982891cc8be1006ff121a9
